project:
  type: website
  output-dir: docs

website:
  title: "CS 5805 Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sahil1509
      - icon: twitter
        href: https://twitter.com/sahil_vt
format:
  html:
    theme: cyborg
    css: styles.css



